### ISSUE TITLE
Add 'Alternatives' section to README

### ISSUE THREAD

**Issue by jspaaks** [nlesc-recruit/CUDA-wrappers#35]
about similar or complementary tools in this space

**Comment by bouweandela** [comment]
That is indeed a similar library, but it wraps the CUDA runtime API. This library aims to wrap the CUDA driver API. See [here](https://docs.nvidia.com/cuda/cuda-runtime-api/driver-vs-runtime-api.html) for an introduction.

**Comment by bouweandela** [comment]
I found this alternative, but it looks like it is not under active development at the moment: https://github.com/apardyl/cudaplusplus

**Comment by bouweandela** [comment]
It looks like [cuda-api-wrappers](https://github.com/eyalroz/cuda-api-wrappers) is planning to support the CUDA Driver API https://github.com/eyalroz/cuda-api-wrappers/issues/9 and NVRTC #228 too, so we should investigate if collaboration is possible instead of starting our own library. @benvanwerkhoven @john-romein @csbnw @svlugt Do you have any experience with that library?

**Comment by bouweandela** [comment]
Another potential alternative: https://github.com/halmd-org/cuda-wrapper

**Comment by john-romein** [comment]
I saw the other wrapper library quite some time ago, but it only supported the runtime API and did not provide any support for runtime compilation, nor support for other CUDA libraries like cuFFT, nvrtc, cuBLAS, ...

**Comment by jspaaks** [comment]
PRs were merged, closing
