### ISSUE TITLE
Shall we keep cufft and cublas out of scope?

### ISSUE THREAD

**Issue by fdiblen** [nlesc-recruit/CUDA-wrappers#41]
The current code has wrappers for fft and blas.
https://github.com/nlesc-recruit/CUDA-wrappers/blob/ea0717593a010c1f3d596839ae46b50b1a43c1d5/cu/cufft.h
https://github.com/nlesc-recruit/CUDA-wrappers/blob/ea0717593a010c1f3d596839ae46b50b1a43c1d5/cu/cublas.h

@benvanwerkhoven @isazi is it fine with you if we keep these two wrappers out of scope and focus on cu.h and nvrtc.h?

**Comment by benvanwerkhoven** [comment]
For the coming sprints I think it's fine to focus on cu.h and nvrtc.h indeed. In the end we do want to also support cufft and cublas, but I think it would be good to focus on cu.h and nvrtc first indeed.

**Comment by fdiblen** [comment]
Thanks of the quick response @benvanwerkhoven

**Comment by jspaaks** [comment]
(current state: https://github.com/nlesc-recruit/CUDA-wrappers/tree/8687120072bb7ef068a2e5599904cb65a94cd8e3/) 

maybe we can 
```shell
git rm -r old/
```

since we'll have the relevant files in the 0.1.0 release

1. https://github.com/nlesc-recruit/CUDA-wrappers/blob/0.1.0/cu/cublas.cc
2. https://github.com/nlesc-recruit/CUDA-wrappers/blob/0.1.0/cu/cublas.h
3. https://github.com/nlesc-recruit/CUDA-wrappers/blob/0.1.0/cu/cufft.cc
4. https://github.com/nlesc-recruit/CUDA-wrappers/blob/0.1.0/cu/cufft.cc

**Comment by jspaaks** [comment]
PR was merged, closing
